### PR TITLE
Jenkins 35096 cppcheck plugin pipeline support 

### PR DESCRIPTION
**Pull request by James-Dengel**
This includes changes for the syntax generator as well as the other changes from Marco Steffan.

### CODE REVIEW

**Comment by loganek** [comment]
Is there anything that blocks merging the PR?

**Comment by James-Dengel** [comment]
@loganek not as far as I know the build should build on java 8.

**Comment by loganek** [comment]
@James-Dengel awesome! @mixalturek, would it be possible to merge it?

**Comment by mixalturek** [comment]
Hi, I'm no longer interested in this plugin and mainly I don't have any time for testing of the changes and releasing of a new version. Please become a maintainer and ask for the permissions.

https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin

**Comment by marcosteffan** [comment]
@James-Dengel  thanks to your work and following the guidelines from https://jenkins.io/doc/developer/plugin-development/pipeline-integration/#basic-update on making plugins pipeline compatible.

If you're fine with that I would merge the branch to master.

**Comment by James-Dengel** [comment]
I have no issue with that at all @marcosteffan  :)

**Comment by amarlier** [comment]
Any news when this will be available?
I'm eager to use cppchek in my pipeline to pubish result

**Comment by jzylkin** [comment]
I would like to know when you are planning to release the next version of cppCheck. It contains bug fixes that our team needs. Thank you for your work on this.

**Comment by canaras81** [comment]
Same question as above: Any plans to release a new version? We'd like this feature..

**Comment by cdunford** [comment]
Also looking forward to a new version - please cut a release.

**Comment by bb-dsa** [comment]
+1 Any news on a new release date.

**Comment by sithiksm** [comment]
We need cppCheck for pipeline and waiting for new version with this fix. Any plan for new release?

**Comment by feliwir** [comment]
Any plans for releasing this? We need it aswell

**Comment by kerrhome** [comment]
We couldn't wait for it to be released, so I made a custom parser using the Warnings plugin.  It works perfectly and you get all of the built-in power of the Warnings plugin, which most have installed already.  If anyone is interested in my setup, let me know and I'll post it.  Since the Warnings plugin plans to add cppcheck as a built-in parser and we already have our customer parser, we actually have no plans to return to this plugin.

**Comment by peter-banfield-fc** [comment]
@kerrhome I would be interested in learning more about your setup.

**Comment by kerrhome** [comment]
image

**Comment by kerrhome** [comment]
You'll find that under Jenkins->Configure in the section "Compiler Warnings".  Look for the "Compiler Warnings" section and add a new parser.  Give it a name like "Cppcheck-<myteam>" so you can differentiate it in the pick list.  The rest should be exactly what I have there.  Then you can implement it in a pipeline like this:

```
warnings (
  parserConfigurations: [[parserName: 'CppCheck-<myteam>', pattern: 'cppcheck.txt']], categoriesPattern: '',
  defaultEncoding: '', excludePattern: '', healthy: '', includePattern: '', messagesPattern: '', unHealthy: ''
)
```

To run cppcheck, use this option (at least):

```
--template="{file},,{line},,{severity},,{id},,{message}"
```

and capture stdout in cppcheck.txt. (adjust things how you like of course).

Hope that helps.

**Pull request merged**
