### PR TITLE
[JENKINS-63808] cppcheck is not compatible with Java 11

### PR DESCRIPTION
**Pull request by xnYi9wRezm**
I did the same changes as in the [performance-signature-dynatrace-plugin](https://issues.jenkins-ci.org/browse/JENKINS-55202?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20performance-signature-dynatrace-pluginl)

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by cfanatic** [comment]
I have built the plugin manually, and can confirm it is working correctly for:
- Jenkins 2.341
- JDK 11.0.14.1

Thanks for your PR!!!

**Comment by basil** [comment]
Closing in favor of #64.

**Comment by basil** [comment]
#64 was released in [1.26](https://github.com/jenkinsci/cppcheck-plugin/releases/tag/cppcheck-1.26).

**Comment by basil** [comment]
@cfanatic @dante999 @il--ya @martyngigg @nurupo @przala @xnYi9wRezm If any of you are still using this plugin, would you be able to test the latest release (1.26) with a recent LTS release of Jenkins running on Java 11 and confirm that the plugin is working? If so, thank you in advance!

**Comment by basil** [comment]
@cfanatic @Dante999 @il--ya @martyngigg @nurupo @przala @xnYi9wRezm Were any of you able to test the latest release?

**Comment by nurupo** [comment]
Sorry, I no longer run Jenkins and not interested in spinning it up to test this.

Would appreciate if you could stop pinging me.

**Comment by xnYi9wRezm** [comment]
> @cfanatic @Dante999 @il--ya @martyngigg @przala @xnYi9wRezm Were any of you able to test the latest release?

Thank you. Yes the latest version works just fine with Java 11+

**Pull request closed without merging**
