### PR TITLE
Merge jenkins-35096_Altran_cppcheck_plugin_pipeline_support into master

### PR DESCRIPTION
**Pull request by michael-doubez**
Simple merge to get pipeline v2.

Bindings with configuration seem broken in freestyle job. It may already be the case in master.

### CODE REVIEW

**Comment by michael-doubez** [comment]
The configuration part seems to be working fine.
It works in Freestyle jobs.

But I still get an error in Pipeline jobs. It may be related to my setup (I have strange errors about Jenkins version required being 2.32.2).

Can somebody try it ?

**Comment by michael-doubez** [comment]
OK. Changing name to start with lowercase did the trick

**Comment by michael-doubez** [comment]
@marcosteffan it is a working version

**Comment by michael-doubez** [comment]
Given all the tries, you could do a squash/rebase rather than a plain merge.

**Comment by marcosteffan** [comment]
IMHO this PR can be dropped since the functionality was already implemented in https://github.com/jenkinsci/cppcheck-plugin/commit/22020cd86f4c3cff5e31e4cfddcf9358464c8139

**Comment by michael-doubez** [comment]
The duplication of config in CppcheckPublisher is wronf and this PR integrated cppcheckPublisher has a named pipeline (not a step).

It allowed me to write a step:
```
    cppcheckPublisher pattern: '**/result.xml'
```
instead of 
```
    step([$class: 'CppcheckPublisher', ....])
```

**Comment by uhafner** [comment]
BTW: Recently I added support for [cppcheck|https://github.com/jenkinsci/warnings-plugin/blob/3.0/src/main/java/io/jenkins/plugins/analysis/warnings/CppCheck.java] in the warnings plug-in. Then you have full pipeline support out of the box. (And you automatically get all the other features of the warnings plug-in at no cost;-)

**Comment by kerrhome** [comment]
When does this get released?  This is awesome, Ullrich.  Thanks.

**Comment by kerrhome** [comment]
We're going to try them out.  Would you like feedback here if we have any?

**Comment by kerrhome** [comment]
Well, this is a problem for us, so we'll not be able to test at this time:

`You must update Jenkins from v2.89.2 to v2.107.3 or later to run this plugin.`

**Comment by michael-doubez** [comment]
Closing pull request since it seems it won't be integrated

**Comment by uhafner** [comment]
A beta version of the upcoming warnings plugin with cppcheck support is now available in the experimental update center. Requires Jenkins 2.81 LTS or newer.

**Pull request closed without merging**
