### PR TITLE
Jenkins 41704 fix error when using job's last cppcheck report

### PR DESCRIPTION
**Pull request by michael-doubez**
I first though it was due to the mixing of thales and jenkins package.
But in fact, the solution consisted in restoring the reference to the job in CppcheckProjectAction.

I kept all the work done since it cleans things up.

### CODE REVIEW

**Comment by michael-doubez** [comment]
@marcosteffan can you please review this PR and #39 please ?

I will use this version of the plugin at work but it would be nice to have an official release

**Comment by marcosteffan** [comment]
For me the changes in https://github.com/jenkinsci/cppcheck-plugin/pull/40/commits/07c9b0f465671686d41f18e7cf568a1be6f159b4 seem OK. 

Though, I am not sure on the implications of dropping the thalesgroup-stuff. @mixalturek do you have any preferences on that?

**Comment by mixalturek** [comment]
Hi, I no longer work on this plugin.

**Comment by michael-doubez** [comment]
I don't know enough about the Jenkins storage system to say f it has an impact or not.
I guess that if some serialisation was done for a Thales class, it may cause the loading to fail.

The only I can think of in what I changed is the ProjectAction. But since the previous development already changed the underlying type from AbstractBuild to Run, I guess it was already broken.

I'll make a try. We may need to make an adaptation to reload correctly existing data.

**Pull request closed without merging**
