### PR TITLE
[Jenkins 41704] Fix linking owner and obtaining graph configuration

### PR DESCRIPTION
**Pull request by robert-shade**

### CODE REVIEW

**Comment by philpem** [comment]
Nice fix. I just hand-built this and installed it into my Jenkins instance, and CPPCheck has started working again :) :+1:

**Comment by zlacelle** [comment]
Also seeing this issue.

**Comment by Hoega** [comment]
Having this issue as well. Would greatly appreciate a merge.

**Comment by robert-shade** [comment]
Until things are merged, you can use the CI build from this PR: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fcppcheck-plugin/detail/PR-46/2/artifacts

Also, you may want to look into migrating to the new warnings-ng, which has cppcheck support. (https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md)  I'm actually in the process of doing that right now for our builds.

**Comment by eoin-oconghaile** [comment]
Thanks @robert-shade. Seems to be working ok so far

**Comment by tozzil** [comment]
Will someone merge this soon?

**Comment by Xenoamor** [comment]
Is there a reason this isn't being merged? I'm hitting the same issue on a multibranch pipeline

**Comment by smuppala01** [comment]
> Until things are merged, you can use the CI build from this PR: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fcppcheck-plugin/detail/PR-46/2/artifacts
> 
> Also, you may want to look into migrating to the new warnings-ng, which has cppcheck support. (https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md) I'm actually in the process of doing that right now for our builds.



> Until things are merged, you can use the CI build from this PR: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fcppcheck-plugin/detail/PR-46/2/artifacts
> 
> Also, you may want to look into migrating to the new warnings-ng, which has cppcheck support. (https://github.com/jenkinsci/warnings-ng-plugin/blob/master/SUPPORTED-FORMATS.md) I'm actually in the process of doing that right now for our builds.

Hi May I know how can I use this, I was using jenkins plugin and facing the same issue as others. This is very critical to finish my task

**Comment by smuppala01** [comment]
Worked for me as well
Steps to have new plugin on your jenkins Instance.
login to jenkins server
cd to /var/lib/jenkins/plugins
rename  cppcheck.jpi       cppcheck.jpi.orig.v1.24
              cppcheck       cppcheck.orig.v1.24
download cppcheck.hpi file from  https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fcppcheck-plugin/detail/PR-46/2/artifacts/
Copy to /var/lib/jenkins/plugins dir 
and restart the jenkins service

**Comment by jimmyw** [comment]
Still waiting...

**Comment by Xenoamor** [comment]
I gave up waiting and migrated to the [warnings-ng](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md) that @robert-shade suggested. That one is in active development and is pretty easy to setup

**Pull request merged**
